<?php include(INC_HTML_TAG); ?>
<?php $hm->Title( __FILE__, RSTR_APP_TITLE, RSTR_ABOUT ); ?>

<head><?php include(INC_HTML_HEADER); ?></head>

<body>

<!-- [BEGIN] Container -->
<div id="container">

<?php include(INC_BODY_HEADER); ?>

<!-- [BEGIN] Main Form -->
<div id="main_div">

<?php //include(INC_FORM_BEGIN); ?>

<?php include(INC_BODY_INFO); ?>

	<!-- [BEGIN] about -->
	<?php echo $hm->SectBegin( RSTR_ABOUT ); ?>

	<div style='overflow:auto;'>
	<table width='99%' border='0' cellpadding='3' cellspacing='1'>

	<tr>
		<td align='left'>

			<div style='font-size:200%;'>
Lancelot's Contacts			</div>

			<div style='margin:10px 0 0 20px;'>
				Generated by <a href='http://www.phpkobo.com/address-book-builder' target='_blank'>
				<span style='font-weight:bold;'>
Address Book Builder</span></a>
v1.2 on
				<span style='font-weight:bold;'>2017-12-03 08:33:07</span>
			</div>

			<div style='margin:10px 0 0 20px;'>
				Base Code : <a href='http://www.phpkobo.com/address_book.php' target='_blank'>
				<span style='font-weight:bold;'>Address Book Script</span></a>
v1.18			</div>

			<div style='margin:10px 0 0 20px;'>
				<a href='http://www.phpkobo.com/address-book-builder?id=25863&ps=YQMcvCvwfI' target='_blank'>
				<span style='font-weight:bold;'>Build a new script based on
				&lt; Lancelot's Contacts &gt;</span>
				</a>
			</div>

		</td>
	</tr>

	<tr>
		<td align='left'>
		</td>
	</tr>

	</table>
	</div>

	<?php echo $hm->SectEnd(); ?>
	<!-- [END] about -->

	<?php echo $hm->SectEndMarker(); ?>

<?php //include(INC_FORM_END); ?>

</div>
<!-- [END] Main Form -->

<?php include(INC_BODY_FOOTER); ?>

</div>
<!-- [END] Container -->

</body>
</html>

<?php include(INC_HTML_END); ?>